@extends('layouts.app')

@section('content')
<section class="login">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-6">
        <div class="girl">
          <img class="img-fluid" src="images/girl.png" alt="">
        </div>
      </div>
      <div class="col-md-6">
        <div class="form_login">
          <div class="txt_reglamento">
            <h2>POL&Iacute;TICA DE TRATAMIENTO DE DATOS PERSONALES</h2>
            <div class="txt_reglamento">
              <p><p class="c4" style="margin: 0cm; text-align: center;" align="center"><span class="c2"><strong><u><span style="font-size: 11.0pt;     ">POL&Iacute;TICA DE TRATAMIENTO DE DATOS PERSONALES</span></u></strong></span></p>
              <p class="c4" style="margin: 0cm; text-align: center;" align="center"><span style="font-size: 11.0pt;     ">&nbsp;</span></p>
              <p class="c0" style="margin: 0cm; text-align: justify;"><span class="c1"><span style="font-size: 11.0pt;     ">La presente Pol&iacute;tica de Tratamiento de Datos Personales e Informaci&oacute;n (en adelante la &ldquo;Pol&iacute;tica&rdquo;), tiene como objetivo implementar las disposiciones contenidas en la Constituci&oacute;n de la Rep&uacute;blica del Ecuador, la Ley de Comercio Electr&oacute;nico, Firmas Electr&oacute;nicas y Mensajes de Datos, la Ley del Sistema Nacional de Registro de Datos P&uacute;blicos, la Ley Org&aacute;nica de Comunicaci&oacute;n, y dem&aacute;s normativa en lo que se refiere exclusivamente a las bases de datos, archivos e informaci&oacute;n que contenga datos personales susceptibles de tratamiento, y explica c&oacute;mo Abbott Laboratorios del Ecuador C&iacute;a. Ltda. (en adelante &ldquo;Abbott), recolecta, almacena, usa, circula y trata informaci&oacute;n que usted nos provee a trav&eacute;s de distintos medios.</span></span></p>
              <p class="c0" style="margin: 0cm; text-align: justify;"><span class="c1"><span style="font-size: 11.0pt;     ">Al aceptar la presente Pol&iacute;tica de Tratamiento de Datos Personales, indica que conoce y autoriza de manera previa, expresa e informada a Abbott, sus filiales y vinculadas, para que sus datos personales puedan ser tratados de acuerdo con lo indicado en esta Pol&iacute;tica. &nbsp;</span></span></p>
              <p class="c0" style="margin: 0cm; text-align: justify;"><span class="c7"><strong><span style="font-size: 11.0pt;     ">DATOS DE CONTACTO DEL RESPONSABLE O ENCARGADO DEL DATO - &Aacute;REA RESPONSABLE DE LA ATENCI&Oacute;N DE CONSULTAS, PETICIONES Y RECLAMOS</span></strong></span><span class="c1"><span style="font-size: 11.0pt;     ">.</span></span></p>
              <p class="c0" style="margin: 0cm; text-align: justify;"><span class="c1"><span style="font-size: 11.0pt;     ">Abbott Laboratorios del Ecuador C&iacute;a. Ltda. (&ldquo;Abbott&rdquo;), es una sociedad legalmente constituida y existente bajo las leyes de la Rep&uacute;blica de Ecuador, constituida mediante escritura p&uacute;blica de 23 de octubre de 1947 en la Notar&iacute;a Tercera de Guayaquil, con domicilio en el Distrito Metropolitano de Quito, y ubicada en la calle Rep&uacute;blica de El Salvador N34-493 y Av. Portugal. Para efectos de esta Pol&iacute;tica, podr&aacute;n contactarnos al siguiente correo electr&oacute;nico habeasdata@abbott.com o al n&uacute;mero de tel&eacute;fono +59323992500 (en adelante, el &ldquo;Responsable del Tratamiento&rdquo;).</span></span></p>
              <p class="c0" style="margin: 0cm; text-align: justify;"><span class="c5"><strong><span style="font-size: 11.0pt;     ">TRATAMIENTO DE LOS DATOS Y FINALIDAD</span></strong></span></p>
              <p class="c0" style="margin: 0cm; text-align: justify;"><span class="c1"><span style="font-size: 11.0pt;     ">El Responsable del Tratamiento, previa autorizaci&oacute;n de los titulares de la informaci&oacute;n (en caso que esta sea requerida), puede obtener informaci&oacute;n de personas naturales, clientes o usuarios, de diferentes fuentes (de acceso p&uacute;blico sin restricci&oacute;n, comercios vinculados, entidades financieras, entidades participantes del sistema de pago, proveedores de servicios de telecomunicaciones, y fuentes propias, entre otros). Tambi&eacute;n es posible que el Responsable del Tratamiento tenga una relaci&oacute;n directa con personas naturales (empleados, proveedores, etc.), que podr&aacute;n optar por brindar informaci&oacute;n personal en conexi&oacute;n con esa relaci&oacute;n. Los tipos de datos personales que recolectamos son datos p&uacute;blicos, semi privados, y no ser&aacute;n recolectados datos sensibles o de menores de edad, a menos que se tenga autorizaci&oacute;n expresa de su titular o su representante legal, de ser el caso y una finalidad v&aacute;lida en este sentido o se haga con el fin de cumplir con una obligaci&oacute;n legal.</span></span></p>
              <p class="c0" style="margin: 0cm; text-align: justify;"><span class="c1"><span style="font-size: 11.0pt;     ">Los usuarios, clientes, trabajadores y proveedores autorizan expresamente al Responsable del Tratamiento a confirmar la informaci&oacute;n personal suministrada acudiendo a entidades p&uacute;blicas, compa&ntilde;&iacute;as especializadas o centrales de riesgo, a sus contactos, o al empleador, as&iacute; como a sus referencias personales, bancarias o laborales, entre otros. Esta informaci&oacute;n ser&aacute; tratada por el Responsable del Tratamiento en forma confidencial.</span></span></p>
              <p class="c0" style="margin: 0cm; text-align: justify;"><span class="c1"><span style="font-size: 11.0pt;     ">Los datos personales proporcionados al Responsable del Tratamiento ser&aacute;n recolectados, almacenados, usados, analizados, circulados, actualizados y reportados para las siguientes finalidades: (i) como elemento de an&aacute;lisis para establecer, mantener y cumplir con las obligaciones o compromisos en una relaci&oacute;n contractual o comercial, cualquiera que sea su naturaleza, (ii) como elemento de an&aacute;lisis para hacer estudios de mercado o investigaciones comerciales o estad&iacute;sticas, (iii) como elemento de an&aacute;lisis y soporte en el cumplimiento de un deber legal, cualquiera que sea su naturaleza (iv) como herramienta para el ofrecimiento de productos o servicios propios o de terceros, (v) como herramienta para el inicio de cualquier cobro prejudicial o judicial, (vi) para que la informaci&oacute;n sea compartida, circulada y usada por Abbott, su matriz, filiales y subordinadas, para cualquiera de los fines aqu&iacute; previstos, (vii) para el adelantamiento de cualquier tr&aacute;mite ante una autoridad p&uacute;blica o una persona o entidad privada, respecto del cual la informaci&oacute;n resulte pertinente, (viii) para que toda la informaci&oacute;n referida al comportamiento crediticio, financiero, comercial, de servicios y datos de la misma naturaleza proveniente de terceros pa&iacute;ses sea consultada, suministrada, reportada, procesada o divulgada, en los t&eacute;rminos y condiciones contenidos en la presente Pol&iacute;tica.</span></span></p>
              <p class="c0" style="margin: 0cm; text-align: justify;"><span class="c5"><strong><span style="font-size: 11.0pt;     ">DERECHOS DE LOS TITULARES</span></strong></span></p>
              <p class="c0" style="margin: 0cm; text-align: justify;"><span class="c1"><span style="font-size: 11.0pt;     ">El titular de los datos personales tiene los siguientes derechos frente al Responsable del Tratamiento:</span></span></p>
              <p class="c0" style="margin: 0cm; text-align: justify;"><span class="c1"><span style="font-size: 11.0pt;     ">1. Conocer, actualizar y rectificar sus datos personales;</span></span></p>
              <p class="c0" style="margin: 0cm; text-align: justify;"><span class="c1"><span style="font-size: 11.0pt;     ">2. Solicitar prueba de la autorizaci&oacute;n otorgada;</span></span></p>
              <p class="c0" style="margin: 0cm; text-align: justify;"><span class="c1"><span style="font-size: 11.0pt;     ">3. Ser informado por el Responsable del Tratamiento previa solicitud, respecto del uso que le ha dado a sus datos personales;</span></span></p>
              <p class="c0" style="margin: 0cm; text-align: justify;"><span class="c1"><span style="font-size: 11.0pt;     ">4. Presentar ante la autoridad competente quejas por infracciones, una vez haya agotado el tr&aacute;mite de consulta o reclamo ante el Responsable del Tratamiento;</span></span></p>
              <p class="c0" style="margin: 0cm; text-align: justify;"><span class="c1"><span style="font-size: 11.0pt;     ">5. Revocar la autorizaci&oacute;n y/o solicitar la supresi&oacute;n del dato cuando en el tratamiento no se respeten los principios, derechos y garant&iacute;as constitucionales y legales, nunca de manera retroactiva; y</span></span></p>
              <p class="c0" style="margin: 0cm; text-align: justify;"><span class="c1"><span style="font-size: 11.0pt;     ">6. Acceder en forma gratuita a sus datos personales que hayan sido objeto de tratamiento.</span></span></p>
              <p class="c0" style="margin: 0cm; text-align: justify;"><span class="c5"><strong><span style="font-size: 11.0pt;     ">COMPLEMENTOS Y DATOS DE REDES SOCIALES:</span></strong></span></p>
              <p class="c0" style="margin: 0cm; text-align: justify;"><span class="c1"><span style="font-size: 11.0pt;     ">Adicionalmente, las aplicaciones a las que usted acceda pueden usar complementos de redes sociales (por ejemplo, el bot&oacute;n "Me gusta" de Facebook, el bot&oacute;n "Compartir en Twitter") para permitirle compartir informaci&oacute;n f&aacute;cilmente. Cuando usted visite dichas aplicaciones, el operador del complemento social podr&iacute;a colocar una cookie en su dispositivo, lo que permite que ese operador reconozca a las personas que han visitado previamente la aplicaci&oacute;n. Si inici&oacute; sesi&oacute;n en el sitio web de las redes sociales (por ejemplo, Facebook, Twitter, Google+) mientras navega en la aplicaci&oacute;n, los complementos sociales permiten que ese sitio web de medios sociales reciba informaci&oacute;n de que ha visitado la aplicaci&oacute;n. Los complementos sociales tambi&eacute;n permiten que el sitio web de medios sociales comparta informaci&oacute;n sobre sus actividades en la aplicaci&oacute;n con otros usuarios de su sitio web de redes sociales. Por ejemplo, Facebook Social Plugins permite que Facebook muestre sus Me gusta y comentarios en nuestras p&aacute;ginas a sus amigos de Facebook. Los complementos sociales de Facebook tambi&eacute;n pueden permitirle ver la actividad de Facebook de sus amigos en la aplicaci&oacute;n. Abbott no controla el contenido de los complementos de redes sociales. Para obtener m&aacute;s informaci&oacute;n acerca de los complementos sociales de otros sitios web de redes sociales, usted debe consultar las pol&iacute;ticas de privacidad y uso compartido de datos de esos sitios.</span></span></p>
              <p class="c0" style="margin: 0cm; text-align: justify;"><span class="c5"><strong><span style="font-size: 11.0pt;     ">PROCEDIMIENTO PARA EJERCER LOS DERECHOS AL HABEAS DATA.</span></strong></span></p>
              <p class="c0" style="margin: 0cm; text-align: justify;"><span class="c1"><span style="font-size: 11.0pt;     ">Los titulares de la informaci&oacute;n podr&aacute;n ejercer los derechos a conocer, actualizar, rectificar, revocar la autorizaci&oacute;n mediante el env&iacute;o de una comunicaci&oacute;n a la direcci&oacute;n y al &aacute;rea indicada en la presente Pol&iacute;tica. Esta comunicaci&oacute;n deber&aacute; contener como m&iacute;nimo lo siguiente:</span></span></p>
              <p class="c0" style="margin: 0cm; text-align: justify;"><span class="c1"><span style="font-size: 11.0pt;     ">1. El nombre, domicilio del titular y medio de contacto para recibir la respuesta como tel&eacute;fono, correo electr&oacute;nico, direcci&oacute;n de residencia.</span></span></p>
              <p class="c0" style="margin: 0cm; text-align: justify;"><span class="c1"><span style="font-size: 11.0pt;     ">2. Los documentos que acrediten la identidad o la representaci&oacute;n de su representado.</span></span></p>
              <p class="c0" style="margin: 0cm; text-align: justify;"><span class="c1"><span style="font-size: 11.0pt;     ">3. La descripci&oacute;n clara y precisa de los datos personales respecto de los cuales el titular busca ejercer alguno de los derechos.</span></span></p>
              <p class="c0" style="margin: 0cm; text-align: justify;"><span class="c1"><span style="font-size: 11.0pt;     ">4. En caso dado, otros elementos o documentos que faciliten la localizaci&oacute;n de los datos personales.</span></span></p>
              <p class="c0" style="margin: 0cm; text-align: justify;"><span class="c1"><span style="font-size: 11.0pt;     ">Una vez recibida la comunicaci&oacute;n por parte del Responsable del Tratamiento, se proceder&aacute; a dar respuesta dentro de los t&eacute;rminos establecidos en la regulaci&oacute;n aplicable.</span></span></p>
              <p class="c0" style="margin: 0cm; text-align: justify;"><span class="c5"><strong><span style="font-size: 11.0pt;     ">MODIFICACI&Oacute;N Y/O ACTUALIZACI&Oacute;N DE LA POL&Iacute;TICA DE PROTECCI&Oacute;N DE DATOS Y MANEJO DE INFORMACI&Oacute;N</span></strong></span></p>
              <p class="c0" style="margin: 0cm; text-align: justify;"><span class="c1"><span style="font-size: 11.0pt;     ">Cualquier cambio sustancial en las pol&iacute;ticas de tratamiento, se comunicar&aacute; de forma oportuna a los titulares de los datos a trav&eacute;s de los medios habituales de contacto.</span></span></p>
              <p class="c0" style="margin: 0cm; text-align: justify;"><span class="c5"><strong><span style="font-size: 11.0pt;     ">VIGENCIA DE LAS POL&Iacute;TICAS DE TRATAMIENTO DE INFORMACI&Oacute;N PERSONAL</span></strong></span></p>
              <p class="c0" style="margin: 0cm; text-align: justify;"><span class="c1"><span style="font-size: 11.0pt;     ">La presente pol&iacute;tica rige a partir de 01 de abril del 2020, y las bases de datos con sus datos personales se mantendr&aacute;n mientras que subsistan las finalidades para los cuales fueron recolectados.</span></span></p>

            </div>
          </div>
        </div>
      </div>
    </section>
    @endsection
