@extends('layouts.app')

@section('content')
<section class="login">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-6">
                <div class="girl">
                    <img class="img-fluid" src="images/girl.png" alt="">
                </div>
            </div>
            <div class="col-md-6">
                <div class="form_login">
                    <div class="txt_reglamento">
                      <p><strong>T&eacute;rminos y Condiciones</strong></p>
<p>Este sitio web&nbsp;<a href="http://www.regresaconpediasure.com/">www.regresaconpediasure.com</a>&nbsp;(en adelante, el &ldquo;Sitio Web&rdquo;) es operado por&nbsp; ABBOTT LABORATORIOS DEL ECUADOR CIA. LTDA., (en adelante, &ldquo;Abbott&rdquo;) y se sujeta a los presentes t&eacute;rminos y condiciones (en adelante, los &ldquo;T&eacute;rminos y Condiciones del Sitio Web&rdquo;).</p>
<p>El Sitio Web est&aacute; destinado a ofrecer informaci&oacute;n en relaci&oacute;n con los productos de la marca Pediasure 3 de la Divisi&oacute;n de Nutrici&oacute;n (ANI) de Abbott (los &ldquo;Productos&rdquo;).</p>
<p>Abbott podr&aacute; modificar los T&eacute;rminos y Condiciones del Sitio Web de tiempo en tiempo, para lo cual le informar&aacute; a los usuarios del Sitio Web (los &ldquo;Usuarios&rdquo;) sobre las modificaciones a los T&eacute;rminos y Condiciones del Sitio Web con una anticipaci&oacute;n razonable para que los Usuarios las conozcan y se familiaricen con ellas. Abbott, a trav&eacute;s del Sitio Web, le pedir&aacute; a los Usuarios que acepten los nuevos T&eacute;rminos y Condiciones del Sitio Web. En cualquier caso, al acceder o utilizar este Sitio Web, usted acepta que ha le&iacute;do, entendido y est&aacute; de acuerdo en comprometerse con estos T&eacute;rminos y Condiciones y con los cambios que eventualmente se realicen a los mismos.</p>
<p>Estos T&eacute;rminos y Condiciones se aplican a personas domiciliadas en la Rep&uacute;blica de Ecuador. Aquellos Usuarios que decidan ingresar al Sitio Web desde otros pa&iacute;ses, lo har&aacute;n bajo su propia iniciativa y es su responsabilidad el sujetarse a las leyes locales que sean aplicables. Cualquier reclamo en relaci&oacute;n con el uso del Sitio Web y el material en &eacute;l contenido est&aacute; regulado por las leyes ecuatorianas.</p>
<p>Su acceso a&nbsp;<a href="http://www.regresaconpediasure.com/">www.regresaconpediasure.com</a>&nbsp;est&aacute; sujeto a los siguientes T&eacute;rminos y Condiciones. Al acceder o utilizar este Sitio Web, usted acepta que ha le&iacute;do, entendido y est&aacute; de acuerdo en comprometerse con estos T&eacute;rminos y Condiciones, as&iacute; como con los t&eacute;rminos de nuestra Pol&iacute;tica de Tratamiento de Datos Personales, la cual podr&aacute; encontrar en este Sitio Web.</p>
<p>El uso de este Sitio Web tras la publicaci&oacute;n por nuestra parte de cualquier cambio a estos T&eacute;rminos y Condiciones constituye su aceptaci&oacute;n de dichos cambios. Si no est&aacute; de acuerdo con estos T&eacute;rminos y Condiciones o no est&aacute; satisfecho con este Sitio Web, el &uacute;nico y exclusivo recurso que tiene es dejar de usar este Sitio Web.</p>
<p>REGISTRO DE USUARIOS</p>
<p>El registro de los Usuarios en este Sitio Web constituye una condici&oacute;n indispensable para que los Usuarios reciban informaci&oacute;n personalizada en relaci&oacute;n con los Productos y servicios de Abbott a trav&eacute;s del mismo. Al aceptar los T&eacute;rminos y Condiciones, cada Usuario entiende esta condici&oacute;n y acepta proporcionar informaci&oacute;n completa, ver&iacute;dica y exacta al registrarse y usar el Sitio Web.</p>
<p>Para poder recibir informaci&oacute;n personalizada, el Usuario deber&aacute; crear una cuenta ("Cuenta de Usuario") de conformidad con las condiciones se&ntilde;aladas en estos T&eacute;rminos y Condiciones del Sitio Web. Para la creaci&oacute;n de la Cuenta de Usuario, el Usuario al ingresar sus datos, declara que los mismos corresponden a informaci&oacute;n veraz, completa y vigente. Para la creaci&oacute;n de la Cuenta de Usuario, el Usuario deber&aacute; diligenciar la siguiente informaci&oacute;n: nombre completo (nombres y apellidos), correo electr&oacute;nico, n&uacute;mero de tel&eacute;fono m&oacute;vil; el diligenciamiento de la fecha de nacimiento es opcional. Esta informaci&oacute;n ser&aacute; tratada de conformidad con estos T&eacute;rminos y Condiciones del Sitio Web y la Pol&iacute;tica de Tratamiento de Datos Personales de Abbott que se encuentra disponible en el Sitio Web. De conformidad con la Pol&iacute;tica de Tratamiento de Datos Personales de Abbott, &eacute;sta cumplir&aacute; con las leyes aplicables en materia de protecci&oacute;n de datos, manteniendo los est&aacute;ndares de seguridad suficientes para impedir cualquier adulteraci&oacute;n, p&eacute;rdida, consulta, uso o acceso no autorizado o fraudulento, y garantizando los derechos de los titulares de los datos.</p>
<p>El Usuario acepta que no podr&aacute; crear una cuenta para alguien distinto al Usuario.</p>
<p>El registro de los Usuarios en el Sitio Web deber&aacute; ser realizado por mayores de edad exclusivamente.</p>
<p>CLAVE DE USUARIO SECRETA</p>
<p>Como parte del proceso de registro, el Usuario deber&aacute; inscribir una clave secreta o contrase&ntilde;a. Para poder acceder a contenido personalizado, el Usuario deber&aacute; ingresar con la contrase&ntilde;a que haya creado al momento del registro, lo que permitir&aacute; el acceso personalizado, confidencial y seguro al Sitio Web. La administraci&oacute;n de esta clave secreta o contrase&ntilde;a es de absoluta responsabilidad del Usuario. Su entrega a terceras personas o su utilizaci&oacute;n por dichas terceras personas, no implicar&aacute; responsabilidad alguna para Abbott.</p>
<p>Siempre que no se haya notificado oportunamente por parte del Usuario la existencia de una violaci&oacute;n a su informaci&oacute;n personal o cuando el Usuario no haya procedido a notificar a Abbott acerca de un uso indebido de sus datos de registro, Abbott no asume ninguna responsabilidad por tales acciones.</p>
<p>DESCARGOS DE RESPONSABILIDAD</p>
<p>Usted reconoce y acepta que:</p>
<ol>
<li>Aunque nos esforzamos por ofrecer en este Sitio Web las &uacute;ltimas novedades relacionadas con nuestros Productos y servicios, y otro tipo de informaci&oacute;n acerca de nuestra compa&ntilde;&iacute;a, no garantizamos la exactitud, la eficacia y la conveniencia del contenido informativo de este Sitio Web. Cada persona asume la responsabilidad total y todos los riesgos derivados del uso de este Sitio Web. La informaci&oacute;n se presenta "tal cual" y puede incluir imprecisiones t&eacute;cnicas o errores tipogr&aacute;ficos. Abbott se reserva el derecho de hacer adiciones, supresiones o modificaciones en la informaci&oacute;n ofrecida en el Sitio Web en cualquier momento sin aviso previo.</li>
</ol>
<p>Abbott no puede garantizar que el Sitio Web funcionar&aacute; sin interrupciones o errores, pero tomar&aacute; las acciones necesarias y realizar&aacute; la debida diligencia, con el fin de ofrecer la mayor disponibilidad del Sitio Web y as&iacute; corregir dentro de la brevedad posible, los errores, omisiones o inexactitudes.</p>
<ol>
<li>HASTA EL M&Aacute;XIMO PERMITIDO POR LA LEY VIGENTE APLICABLE EN LA REP&Uacute;BLICA DE ECUADOR, ABBOTT NO HACE DECLARACIONES NI GARANT&Iacute;AS DE NING&Uacute;N TIPO O NATURALEZA CON RESPECTO A LA INFORMACI&Oacute;N O CONTENIDO PUBLICADO EN ESTE SITIO WEB. POR ESTE MEDIO, ABBOTT QUEDA EXENTO DE TODAS LAS DECLARACIONES Y GARANT&Iacute;AS, YA SEA EXPRESAS O IMPL&Iacute;CITAS, CREADAS POR LEY, CONTRATO U OTRO MEDIO, INCLUIDAS ENTRE OTRAS, TODAS LAS GARANT&Iacute;AS DE COMERCIALIZACI&Oacute;N, ADAPTACI&Oacute;N A UN PROP&Oacute;SITO ESPEC&Iacute;FICO, T&Iacute;TULO O NO INFRACCI&Oacute;N. EN NING&Uacute;N CASO, ABBOTT SERA RESPONSABLE POR DA&Ntilde;OS DE CUALQUIER TIPO O NATURALEZA, INCLUIDOS ENTRE OTROS, DA&Ntilde;OS DIRECTOS, INDIRECTOS, ESPECIALES (INCLUIDO LUCRO CESANTE) EMERGENTES O FORTUITOS EN RELACI&Oacute;N CON LA EXISTENCIA O USO DE ESTE SITIO WEB Y/O LA INFORMACI&Oacute;N O EL CONTENIDO PUBLICADO EN ESTE SITIO WEB, INDEPENDIENTEMENTE DE SI ABBOTT HA SIDO NOTIFICADO DE LA POSIBILIDAD DE DICHOS DA&Ntilde;OS.</li>
<li>Hasta el m&aacute;ximo permitido por la ley vigente aplicable en la Rep&uacute;blica de Ecuador, Abbott no es responsable ni ofrece garant&iacute;as de ning&uacute;n tipo por la exactitud, la eficacia, la oportunidad y la conveniencia de la informaci&oacute;n o el contenido obtenido de terceros, incluidos los hiperv&iacute;nculos hacia o desde sitios de terceros. Salvo que se disponga lo contrario en este Sitio Web, Abbott no editar&aacute;, censurar&aacute;, ni de otro modo controlar&aacute; el contenido proporcionado por terceros en cualquier tablero de anuncios, sala de chat u otros foros similares publicados en el Sitio Web. Dicha informaci&oacute;n debe, por lo tanto, considerarse sospechosa y no recibe la aprobaci&oacute;n de Abbott.</li>
<li>Este Sitio Web puede contener declaraciones proyectivas que reflejan las expectativas actuales de Abbott con respecto a eventos futuros y el desarrollo de negocios. Dichas declaraciones implican riesgos e incertidumbres. Los avances o resultados reales podr&iacute;an diferir sustancialmente de los proyectados y dependen de una serie de factores, que incluyen el &eacute;xito de los programas de investigaci&oacute;n en curso, los resultados de ensayos cl&iacute;nicos pendientes o futuros, la comercializaci&oacute;n continua de sus Productos, las aprobaciones regulatorias de sus Productos, la validez y la vigencia de sus patentes, la estabilidad de sus relaciones comerciales y las condiciones econ&oacute;micas en general, entre otros. Abbott tiene la intenci&oacute;n de actualizar este Sitio Web de forma peri&oacute;dica, pero no asume ninguna obligaci&oacute;n de actualizar los contenidos.</li>
</ol>
<p>SOBRE EL USO</p>
<p>Usted entiende, reconoce y acepta lo siguiente:</p>
<ol>
<li>Si usa este Sitio Web, usted acepta no interrumpir ni interceptar la informaci&oacute;n electr&oacute;nica publicada en este Sitio Web o en cualquiera de nuestros servidores. Tambi&eacute;n acepta no intentar evadir ninguna de las caracter&iacute;sticas de seguridad de nuestro Sitio Web, y se compromete a respetar todas las leyes, normas y reglamentos locales e internacionales aplicables.</li>
<li>Usted otorga a Abbott el derecho de usar todo el contenido que usted cargue o que transmita de alguna otra manera a este Sitio Web, sujeto a estos T&eacute;rminos y Condiciones y a la Pol&iacute;tica de Tratamiento de Datos Personales de Abbott.</li>
<li>Salvo que Abbott lo indique y acuerde expresamente con antelaci&oacute;n, no se establecer&aacute; ninguna relaci&oacute;n confidencial en el caso de que alg&uacute;n usuario de este Sitio Web deba hacer cualquier comunicaci&oacute;n oral, escrita o electr&oacute;nica a Abbott (como por ejemplo comentarios, preguntas, observaciones, sugerencias, ideas, etc.). Si alguno de los Sitios Web de Abbott requiere o solicita que se proporcione dicha informaci&oacute;n y que esta contenga datos personales (por ejemplo, nombre, direcci&oacute;n, n&uacute;mero de tel&eacute;fono, etc), Abbott la obtendr&aacute;, la usar&aacute; y mantendr&aacute; de manera coherente con su Pol&iacute;tica de Tratamiento de Datos Personales y observando la normatividad aplicable en Ecuador en materia de protecci&oacute;n de datos.&nbsp;&nbsp; Respecto de las comunicaciones orales, escritas o electr&oacute;nicas que no contengan datos personales, Abbott tendr&aacute; libertad para reproducir, publicar o bien utilizar dicha informaci&oacute;n para cualquier prop&oacute;sito, como investigaci&oacute;n, desarrollo, fabricaci&oacute;n, uso o venta de productos que incorporen dicha informaci&oacute;n. El remitente de cualquier informaci&oacute;n a Abbott es totalmente responsable de su contenido, incluidas su veracidad y exactitud y la no violaci&oacute;n por su parte de los derechos de propiedad o privacidad de cualquier otra persona. En todo caso, Abbott no responder&aacute; bajo ninguna circunstancia de la informaci&oacute;n o contenidos que se incluyan en secciones p&uacute;blicas de este Sitio Web, a las cuales cualquier tercero pueda acceder y, en dicho sentido, conocer la informaci&oacute;n o contenidos que se publiquen en los mismos.</li>
<li>Al aceptar los T&eacute;rminos y Condiciones del Sitio Web o acceder al mismo, el Usuario declara y se compromete a que no realizar&aacute;, ni intentar&aacute; o ayudar&aacute; a otra persona a realizar la violaci&oacute;n de los T&eacute;rminos y Condiciones del Sitio Web.</li>
<li>El Usuario declara que se abstendr&aacute; de utilizar el Sitio Web para:</li>
<li>Cargar, descargar, enviar, transmitir o almacenar contenido que sea il&iacute;cito, fraudulento, falso, perjudicial, doloso, calumnioso, difamatorio, abusivo, violento, obsceno, vulgar, invasivo de la privacidad de ajenos, ofensivo de car&aacute;cter racial o &eacute;tnico, o de otra manera censurable.</li>
<li>Participar en cualquier violaci&oacute;n de los derechos de autor u otra violaci&oacute;n de propiedad intelectual, o revelar cualquier secreto industrial o informaci&oacute;n confidencial por lo que se incumple un contrato de confidencialidad, de empleo o de no divulgaci&oacute;n.</li>
<li>Cargar, publicar, almacenar o de otra manera introducir o subir al Sitio Web cualquier material que contenga virus o cualquier otro c&oacute;digo, archivo o programas de computadora con la intenci&oacute;n de da&ntilde;ar, interferir con o limitar la operaci&oacute;n habitual del Sitio Web.</li>
<li>Interferir o interrumpir el funcionamiento del Sitio Web (por medio de cualquier m&eacute;todo deliberado o automatizado).</li>
<li>Intentar o realizar cualquier actividad il&iacute;cita a trav&eacute;s del Sitio Web.</li>
</ol>
<p>CONTENIDO DEL SITIO WEB</p>
<p>El contenido del Sitio Web no debe usarse para determinar el tratamiento de ning&uacute;n tipo de afecci&oacute;n, enfermedad o similares.</p>
<p>Este Sitio Web, la informaci&oacute;n y los recursos relacionados con la salud no tienen como objetivo ni deben interpretarse como asesoramiento o la prestaci&oacute;n de servicios m&eacute;dicos, de enfermer&iacute;a o de cuidado de la salud profesional ni como la pr&aacute;ctica de la medicina, la enfermer&iacute;a o el cuidado de la salud profesional.</p>
<p>Salvo que Abbott lo indique y acuerde expresamente con antelaci&oacute;n, ning&uacute;n director, empleado, agente o representante de Abbott, se dedica a proporcionar asesoramiento, diagn&oacute;stico o tratamiento m&eacute;dico ni otros servicios m&eacute;dicos que de alguna manera creen una relaci&oacute;n m&eacute;dico-paciente a trav&eacute;s de este Sitio Web.</p>
<p>El Usuario declara que verificar&aacute; la informaci&oacute;n del Producto (incluso los prospectos del empaque) con respecto a dosificaci&oacute;n, precauciones, advertencias, interacciones y contraindicaciones antes de consumir o usar cualquier Producto al que se haga referencia en el Sitio Web.</p>
<p>PROPIEDAD INTELECTUAL</p>
<p>La informaci&oacute;n, los documentos y los gr&aacute;ficos relacionados publicados en este Sitio Web (la "Informaci&oacute;n") son propiedad exclusiva de Abbott, con excepci&oacute;n de la informaci&oacute;n que proporcionan terceros proveedores contratados por Abbott. Se concede permiso para usar la informaci&oacute;n, siempre que (1) el aviso de derechos de autor aparezca en todas las copias; (2) el uso de la Informaci&oacute;n sea solo para uso informativo y no comercial o personal; (3) no se modifique la Informaci&oacute;n de ninguna manera; y (4) ning&uacute;n gr&aacute;fico disponible en este Sitio Web se utilice separadamente del texto que lo acompa&ntilde;a. Abbott no es responsable de los contenidos que proporcionan terceros proveedores, y queda prohibida la distribuci&oacute;n de este material sin el permiso del propietario de los derechos de autor de los mismos. Con excepci&oacute;n de lo permitido anteriormente, no se concede ninguna licencia o derecho, expreso o impl&iacute;cito, a ninguna persona bajo ninguna patente, marca registrada u otro derecho de propiedad de Abbott.</p>
<p>No se podr&aacute; hacer uso de ninguna marca comercial registrada, nombres comerciales, imagen comercial ni productos de Abbott en este Sitio Web sin la previa autorizaci&oacute;n por escrito de esta &uacute;ltima, excepto para identificar los productos o servicios de la compa&ntilde;&iacute;a.</p>
<p>PRIVACIDAD Y SEGURIDAD</p>
<p>Abbott se compromete a proteger su privacidad en l&iacute;nea. Somos conscientes de la importancia de la privacidad para los clientes y visitantes de nuestro Sitio Web. El uso que damos a la informaci&oacute;n de identificaci&oacute;n personal se rige por nuestra Pol&iacute;tica de Tratamiento de Datos Personales, y al acceder y usar nuestro Sitio Web, usted acepta que quedar&aacute; limitado por esa Pol&iacute;tica.</p>
<p>LIMITACI&Oacute;N DE RESPONSABILIDAD</p>
<p>Abbott no asume ninguna responsabilidad por los materiales, la informaci&oacute;n ni las opiniones proporcionadas, publicadas o, de otro modo, disponibles a trav&eacute;s de este Sitio Web. La confianza en estos materiales, informaci&oacute;n y opiniones corre bajo su propio riesgo. Abbott declina toda responsabilidad por lesiones o da&ntilde;os que resulten del uso de este Sitio Web o el contenido del mismo.</p>
<p>ESTE SITIO WEB DE ABBOTT, EL CONTENIDO DEL SITIO Y LOS PRODUCTOS Y SERVICIOS QUE OFRECE O QUE EST&Aacute;N DISPONIBLES A TRAV&Eacute;S DE ESTE SITIO WEB SE OFRECEN "TAL CUAL" Y "SEG&Uacute;N DISPONIBILIDAD", CON TODOS SUS DEFECTOS. EN NING&Uacute;N CASO ABBOTT, SUS PROVEEDORES O SUS RESPECTIVOS DIRECTORES, EMPLEADOS O AGENTES (EN LO SUCESIVO LAS "PARTES DE ABBOTT") SER&Aacute;N RESPONSABLES DE DA&Ntilde;OS DE NING&Uacute;N TIPO, BAJO NINGUNA TEOR&Iacute;A LEGAL, DERIVADOS DE O EN RELACI&Oacute;N CON EL USO QUE USTED HAGA, O SU IMPOSIBILIDAD DE HACERLO, DE ESTE SITIO WEB, EL CONTENIDO DEL SITIO, LOS SERVICIOS PRESTADOS EN O A TRAV&Eacute;S DE ESTE SITIO WEB O CUALQUIER SITIO VINCULADO, INCLUIDOS DA&Ntilde;OS ESPECIALES, INDIRECTOS, PUNITIVOS, INCIDENTALES, EJEMPLARES O DERIVADOS, ENTRE ELLOS LESIONES PERSONALES, LUCRO CESANTE O DA&Ntilde;O COMO RESULTADO DE DEMORA, INTERRUPCI&Oacute;N EN EL SERVICIO, VIRUS, ELIMINACI&Oacute;N DE ARCHIVOS O COMUNICACIONES ELECTR&Oacute;NICAS, O ERRORES, OMISIONES U OTRAS INEXACTITUDES EN ESTE SITIO WEB O EL CONTENIDO DEL SITIO, EXISTIENDO O NO NEGLIGENCIA POR PARTE ABBOTT Y HAYA SIDO O NO ABBOTT NOTIFICADO DE LA POSIBILIDAD DE DICHOS DA&Ntilde;OS.</p>
<p>RESPONSABILIDAD DEL USUARIO</p>
<p>Al ingresar a este Sitio Web, usted adquiere el compromiso de suministrar informaci&oacute;n personal correcta y verdadera, as&iacute; como proceder a la actualizaci&oacute;n de sus datos cada vez que se requiera. Se le proh&iacute;be poner en, o transmitir a, o desde este sitio web, cualquier material ilegal, amenazador, calumniador, difamatorio, obsceno, escandaloso, pornogr&aacute;fico o profano, o cualquier otro material que pudiera dar lugar a cualquier responsabilidad civil o penal en los t&eacute;rminos de la ley.</p>
<p>Usted acepta no utilizar ning&uacute;n dispositivo, software, rutina ni datos para obstruir o intentar obstruir el funcionamiento correcto de este Sitio Web o toda actividad realizada en este Sitio Web. Adem&aacute;s, acepta no utilizar ni intentar utilizar ning&uacute;n motor, software, herramienta, agente, datos u otro dispositivo o mecanismo (incluidos, entre otros, exploradores, ara&ntilde;as, robots, personajes digitales o agentes inteligentes) para navegar o buscar en este Sitio Web, que no sea el motor de b&uacute;squeda o los agentes de b&uacute;squeda brindados por Abbott o los exploradores en general disponibles para el p&uacute;blico.</p>
<p>INDEPENDENCIA DE DISPOSICIONES</p>
<p>En caso de que una o m&aacute;s de las disposiciones contenidas en los presentes T&eacute;rminos y Condiciones sean consideradas nulas, ilegales o ineficaces en cualquier aspecto, la validez, legalidad y exigibilidad o eficacia del resto de las disposiciones del presente documento no se ver&aacute;n afectadas o anuladas por dicha circunstancia.</p>
<p>GENERAL</p>
<p>Al hacer clic en acepto o acceder al Sitio Web, el Usuario declara que acepta que estos T&eacute;rminos y Condiciones del Sitio Web describen el acuerdo completo entre el Usuario y Abbott. Este Sitio Web fue creado y es operado bajo las leyes de la Republica de Ecuador. Las leyes de la Republica de Ecuador controlar&aacute;n los t&eacute;rminos y condiciones previstos en estos T&eacute;rminos y Condiciones del Sitio Web, sin dar efecto a ning&uacute;n principio de conflicto de leyes. Si una autoridad competente considera que alguna disposici&oacute;n de estos T&eacute;rminos y Condiciones del Sitio Web es inv&aacute;lida o no aplicable, usted acepta que las dem&aacute;s disposiciones de estos T&eacute;rminos y Condiciones del Sitio Web permanecer&aacute;n en plena vigencia y efecto.</p>
<p>Conoce aqu&iacute; nuestra&nbsp;<a href="https://www.pediasure.abbott/ec/politica-de-privacidad.html"><strong>Pol&iacute;tica de Tratamiento de Datos Personales</strong></a></p>
<p>&nbsp;</p>

</div>



            </div>
        </div>
            </div>
        </div>
    </div>
</section>
@endsection
